name: PHP Linter

on:
    pull_request: null
    push:
        branches:
            - "main"

env:
    # see https://github.com/composer/composer/issues/9368#issuecomment-718112361
    COMPOSER_ROOT_VERSION: "dev-main"

jobs:
    php_linter:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.1
                    coverage: none

            -   run: composer create-project php-parallel-lint/php-parallel-lint php-parallel-lint

            -   run: php-parallel-lint/parallel-lint src config tests
